### ISSUE TITLE
Hub Embed 

### ISSUE THREAD

**Issue by fowlerj9** [esridc/covid-report#1]
Hey,

When I go to embed a graphic in Hub using iframe element from layout I get "We're sorry, the page you're looking for can't be found". Please advise.

- https://esridc.github.io/covid-report/?county=Orange%2C+NC
  - https://bao.arcgis.com/InfographicsPlayer/ArcGISPro/BA_Covid19_Counties/37135.html
- https://esridc.github.io/covid-report/?county=Cumberland%2C+NC
  - https://bao.arcgis.com/InfographicsPlayer/ArcGISPro/BA_Covid19_Counties/37051.html

![Snag_54ead4a](https://user-images.githubusercontent.com/25531578/77476717-7672c380-6df1-11ea-8d13-a091bd88f70c.png)

**Comment by ajturner** [comment]
Currently you need to embed the app. There is an issue with AGO Auth that we’re planning to resolve, but this works today

https://esridc.github.io/covid-report/?county=Cumberland%2C+NC&embed=true

**Comment by ajturner** [comment]
I updated the site to use this as the recommended embed url. Thanks for the report!
